POST  http://localhost:3000/reports
content-type: application/json

{
    "make":"toyota",
    "model":"corola",
    "year":1980,
    "mileage" : 1000,
    "lng":0,
    "lat":0,
    "price":5000
}


### Approve an existing report
PATCH http://localhost:3000/reports/5
Content-Type: application/json

{
    "approved":false
}


### Get an Estimate for an existing vehicle
GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=2000&year=1980