### Create New User
POST http://localhost:3000/auth/signup
content-type : application/json

{
    "email" : "rajvivek10.brain@gmail.com",
    "password" : "Brain@2022"
}

###Signin User
POST http://localhost:3000/auth/signin
content-type : application/json

{
    "email" : "rajvivek.brain@gmail.com",
    "password" : "Brain@2022"
}

### Find a particular user with a given Id
GET  http://localhost:3000/auth/4



### Find all users with a given email
GET http://localhost:3000/auth?email=me.kumarrahul@gmail.com


### Delete a user given id

DELETE  http://localhost:3000/auth/7




### Update a user 
PATCH  http://localhost:3000/auth/2
content-type: application/json

{
    "email" : "me.kumarrahul@gmail.com"
}



### Set Session (Set color)
 
GET http://localhost:3000/auth/colors/orange

### Get the color
GET http://localhost:3000/auth/colors